### ISSUE TITLE
Codegen not showing array at Delegator.ts

### ISSUE THREAD

**Issue by youssefea** [subquery/subql-cosmos#150]
When using yarn codegen to generate types from a GraphQL schema, it seems that the generation is incorrect for array types in the `Constructor`. Specifically, when defining a field of type BigInt[], the generated TypeScript code shows the field as `bigint`, not `bigint[]`.

**To Reproduce**

Define a GraphQL schema with an entity that contains a BigInt[] field. Here's an example:

`type Delegator @entity {
  id: ID!
  rewards: [BigInt!]!
  totalRewards: BigInt!
}`

- Run `yarn codegen`.

The resulting TypeScript code in `Delegator.ts` contructor does not correctly reflect the BigInt[] type for the rewards field. It's generated as bigint instead of bigint[].

**Expected behavior**

The rewards field should be generated as bigint[], reflecting the BigInt[] type defined in the GraphQL schema.

**Desktop:**
OS: Windows 11

**Screenshot:**
<img width="204" alt="image" src="https://github.com/subquery/subql-cosmos/assets/81751092/f4e51894-7405-4354-b3d3-6305f3574712">

**Comment by stwiname** [comment]
I can't reproduce this. I assume it was fixed at some point
