### ISSUE TITLE
src/types directory still being pushed despite being in .gitignore

### ISSUE THREAD

**Issue by youssefea** [subquery/subql-cosmos#151]
**Description**
Despite the src/types directory being listed in the .gitignore file, changes to this directory are still being tracked and pushed.
This is apparently the case for many projects in the [cosmos starter repo](https://github.com/subquery/cosmos-subql-starter):

- [persistence-starter](https://github.com/subquery/cosmos-subql-starter/tree/main/Persistence/persistence-starter)
- [axelar-starter](https://github.com/subquery/cosmos-subql-starter/tree/main/Axelar/axelar-starter)
- [sei-starter](https://github.com/subquery/cosmos-subql-starter/tree/main/Sei/sei-starter)

So this is not just an issue on my side. Whoever has built these project starters have had this issue too.

This is a minor issue, but @jamesbayly raised it in one of his latest reviews of my code and I noticed it.

**To Reproduce**

Clone a branch of the [cosmos starter repo](https://github.com/subquery/cosmos-subql-starter) and use the `subql init` to start a new boilerplate (eg. Sei)
Make changes to any file in the src/types directory.
Try to commit these changes.
Push the changes to the branch.
Notice that the changes to src/types have been pushed, even though this directory is listed in .gitignore.

**Expected behavior**
Changes to the src/types directory should be ignored by Git and not be pushed to the repository.

**Screenshots**
<img width="544" alt="image" src="https://github.com/subquery/subql-cosmos/assets/81751092/2c76331a-995a-43e8-8bcc-9b389a22d731">

**Desktop :**

OS: Windows 11

**What I tried to do already**
Untrack the src/types directory using the following command in the project's root directory:

`git rm -r --cached src/types`

This command removes the directory from Git's tracking, but does not delete it from the local file system. After running this command, any changes to files in src/types should be ignored by Git. Still does not ignore it.

**Comment by bz888** [comment]
https://github.com/subquery/cosmos-subql-starter/pull/35
`.gitignore` should be added to each project as well.
