### ISSUE TITLE
Provide starters for more projects

### ISSUE THREAD

**Issue by stwiname** [subquery/subql-cosmos#37]
We should provide starter projects for each of the [supported dictionaries](https://github.com/subquery/cosmos-subql-dictionaries)

Todo:
- [ ] Add a branch to https://github.com/subquery/juno-subql-starter for each of these networks
    - [ ] Update the endpoint and chainId
    - [ ] Add the dictionary endpoint
    - [ ] Add any necessary chain types
- [ ] Update [templates](https://github.com/subquery/templates/) to include all these projects
- [x] Rename https://github.com/subquery/juno-subql-starter to https://github.com/subquery/cosmos-subql-starter

**Comment by sascha1337** [comment]
I’ll try to get stargaze up
